version: "3.8"

services:

#==================================================
# Ollama service for embedding
#==================================================

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama  
    networks:
      - appnet
    restart: unless-stopped

  ollama-init:
    image: ollama/ollama:latest
    depends_on:
      - ollama
    volumes:
      - ollama_data:/root/.ollama  
    networks:
      - appnet
    environment:
      - OLLAMA_HOST=http://ollama:11434   
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      ollama pull nomic-embed-text;
      echo 'DONE';
      tail -f /dev/null
      "
#==================================================
# Redis service for Celery broker
#==================================================

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - appnet


  worker:
    build:
      context: ./document_processing_pipeline
    command: celery -A celeryModule.tasksCelery worker -l info
    depends_on:
      - redis
      - ollama
    networks:
      - appnet

#==================================================
# FastAPI service
#==================================================

  fastapi:
    container_name: fastapi
    build:
      context: ./document_processing_pipeline
    ports:
      - "5000:5000"
    depends_on:
      - minio
    volumes:
      - ./document_processing_pipeline:/app
    networks:
      - appnet
    restart: unless-stopped

#==================================================
# MinIO service for S3-compatible storage
#==================================================


  minio:
    container_name: minio
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_NOTIFY_WEBHOOK_ENABLE_1: "on"
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_1: "http://fastapi:5000/minio-event"
      MINIO_NOTIFY_WEBHOOK_QUEUE_LIMIT_1: "10"
      MINIO_NOTIFY_WEBHOOK_AUTH_TOKEN_1: ""
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - appnet

  mc-setup:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 minio minio123;
      mc mb myminio/mybucket;
      mc event add myminio/mybucket arn:minio:sqs::1:webhook --event put,delete;
      echo 'Konfiguracja zakończona!';
      tail -f /dev/null
      "
    networks:
      - appnet






volumes:
  minio_data:
  ollama_data:
  # qdrant_data:


networks:
  appnet:
    driver: bridge