services:
  minio:
    image: minio/minio
    container_name: minio

    ports:
      - "${MINIO_SERVER_AD}:${MINIO_SERVER_AD}"
      - "${MINIO_SERVER_HTTP_HOST}:${MINIO_SERVER_HTTP_HOST}"

    environment:
      MINIO_ROOT_USER: ${USER_NAME_ACCES}
      MINIO_ROOT_PASSWORD: ${USER_PASSWORD_ACCES}

    volumes:
      - ${MINIO_DATA}:/data:Z

    command: server /data --console-address ":9001"

    restart: unless-stopped
