from collections.abc import Callable

from core.logger_config import logger
from infrastructure.celery.client import celery_app
from services.storage_events.events import EventType
from services.storage_events.handlers import handle_object_created, handle_object_removed

methods: dict[EventType, Callable] = {
    EventType.OBJECT_REMOVED_DELETE: handle_object_removed,
    EventType.OBJECT_CREATED: handle_object_created,
}


@celery_app.task
def webhook_minio_events(data: dict) -> None:
    """
    Celery task responsible for processing MinIO webhook events.

    The task receives events generated by MinIO and dispatches them
    to the appropriate event handler depending on the event type.

    Supported events:

    - ``s3:ObjectCreated:Put``
        Starts document ingestion and embedding generation.

    - ``s3:ObjectRemoved:Delete``
        Removes document embeddings from Qdrant.

    Args:
        data (dict):
            MinIO webhook event payload.

    Returns:
        None

    Raises:
        Exception:
            Any exception raised during event handling is caught,
            logged, and does not terminate the Celery worker.
    """

    try:
        event_type = data.get("EventName")

        logger.debug(f"Event type: {event_type}")

        handler = methods.get(EventType(event_type))

        if handler:
            logger.debug(f"Found handler for event type: {event_type}")

            handler(data)

        else:
            logger.warning(f"No handler found for event type: {event_type}")

    except Exception as e:
        logger.error(f"Error processing MinIO event: {e}", exc_info=True)
